name: CMake

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  PYTHON_VERSION: 3.8
  CONAN_PROFILE: ./conan/profiles/linux
  BUILD_THREADS: 1

jobs:
  
  build:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup python 
      uses: actions/setup-python@v2
      with:
          python-version: ${{env.PYTHON_VERSION}}
    
    - name: Setup build tools
      run: |
          python -m pip install --upgrade pip
          pip install conan
          pip install ninja
          conan user
    
    - name: Build
      run: sh .travis/build_unix.sh
      env:
        CONAN_PROFILE: ${{env.CONAN_PROFILE}}
        BUILD_THREADS: ${{env.BUILD_THREADS}}
