name: Release

on:
  push:
    tags:
      - 'v*.*.*'

env:
  PYTHON_VERSION: 3.8
  REMOTE_URL: https://gipeto.jfrog.io/artifactory/api/conan/gipeto-conan
 
jobs:
  
  release-package:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: Setup python 
      uses: actions/setup-python@v2
      with:
          python-version: ${{env.PYTHON_VERSION}}
    
    - name: Setup conan
      run: |
          python -m pip install --upgrade pip
          pip install conan
          export CONAN_REVISIONS_ENABLED=1
          conan remote add conan-remote ${CONAN_REMOTE}
          conan user -p ${CONAN_PASSWORD} -r conan-remote ${CONAN_USERNAME}
          
      env:
         CONAN_USERNAME: ${{ secrets.CONAN_USERNAME }}
         CONAN_PASSWORD: ${{ secrets.CONAN_PASSWORD }}
         CONAN_REMOTE: ${{ env.REMOTE_URL }}

    - name: Get tag version
      run: echo "RECIPE_VERSION=${GITHUB_REF#refs/*/v}" >> $GITHUB_ENV
   
    - name: Export and upload
      run: |
          export CONAN_REVISIONS_ENABLED=1
          conan export ${WORKSPACE} conan/stable
          conan upload amgs/${RECIPE_VERSION}@conan/stable -r conan-remote --no-overwrite
      env:
         CONAN_REMOTE: ${{ env.REMOTE_URL }}
         WORKSPACE: ${{ github.workspace }}
