name: Windows-2019

on:
  push:
    branches: [ $default-branch, master ]
  pull_request:
    branches: [ $default-branch, master ]

env:
  PYTHON_VERSION: 3.8
  CONAN_PROFILE: ${{ github.workspace }}/.conan/profiles/windows
  BUILD_THREADS: 8

jobs:
  
  build-and-package:
  
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2

    - name: Setup python 
      uses: actions/setup-python@v2
      with:
          python-version: ${{env.PYTHON_VERSION}}
    
    - name: Setup build tools
      run: |
          python -m pip install --upgrade pip
          pip install conan
          pip install ninja
          conan user
    
    - name: Build
      run: ${{ github.workspace }}/.github/ci/build_windows.bat
      env:
        CONAN_PROFILE: ${{env.CONAN_PROFILE}}
        BUILD_THREADS: ${{env.BUILD_THREADS}}

    - name: Test conan package
      run: bash ${{ github.workspace }}/.github/ci/test_windows_packaging.bat
      env:
        CONAN_PROFILE: ${{env.CONAN_PROFILE}}
